name: Build GeckoView for Android

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write
env:
  IS_PROD: 1
  GECKOVIEW_VERSION: 156.0.13
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24
      - run: |
          free -lh
      - name: Free Disk Space (Ubuntu)
        uses: BRAINSia/free-disk-space@v2
        with:
          tool-cache: true
          mandb: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      - name: Checkout gecko-dev
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            unzip \
            zip \
            wget \
            curl \
            git \
            file
      - name: Bootstrap toolchain
        run: |
          ./mach --no-interactive bootstrap --application-choice="GeckoView/Firefox for Android"
        env:
          MOZ_AUTOMATION: 1
      - run: |
          ./mach doctor

      - name: Setup mozconfig
        run: |
          # 使用 > 覆盖写入，确保文件只包含以下两行
          cat > mozconfig <<EOF
          ac_add_options --enable-project=mobile/android
          ac_add_options MOZILLA_OFFICIAL=1
          ac_add_options --enable-update-channel=release
          ac_add_options --enable-optimize
          ac_add_options --disable-debug
          EOF
          # （可选）显示内容以验证
          cat mozconfig
      - name: Build GeckoView
        run: |
          ./mach build
      - name: Create Maven bundle zip
        run: |
          cd obj-x86_64-unknown-linux-android/gradle/maven
          zip -r ${{ github.workspace }}/central-bundle.zip io

      - name: Upload to Sonatype Central
        run: |
          curl --request POST \
            --verbose \
            --header 'Authorization: Bearer ${{ secrets.SONATYPE_TOKEN }}' \
            --form bundle=@central-bundle.zip \
            https://central.sonatype.com/api/v1/publisher/upload


      - name: Rename AAR to include -x86
        run: |
          for f in obj-x86_64-unknown-linux-android/gradle/build/mobile/android/geckoview/outputs/aar/*.aar; do
              if [ -f "$f" ]; then
                  mv "$f" "${f%.aar}-x86.aar"
              fi
          done

