name: Build GeckoView for Android

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: BRAINSia/free-disk-space@v2
        with:
          tool-cache: true
          mandb: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true
      - name: Checkout gecko-dev
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            unzip \
            wget \
            curl \
            git \
            file
      - name: Bootstrap toolchain
        run: |
          ./mach --no-interactive bootstrap --application-choice="GeckoView/Firefox for Android"
        env:
          MOZ_AUTOMATION: 1
      - run: |
          ./mach doctor
      - name: Build GeckoView
        run: |
          ./mach build

      - run: |
          ls -l
          ls -d obj-*

      - name: Rename AAR to include -x86
        run: |
          for f in obj-*/gradle/build/mobile/android/geckoview/outputs/aar/*.aar; do
            if [ -f "$f" ]; then
              mv "$f" "${f%.aar}-x86.aar"
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          files: |
            obj-*/gradle/build/mobile/android/geckoview/outputs/aar/*-x86.aar
          tag_name: ${{ github.ref_name }}

      - name: Upload AAR artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: geckoview-aar
          path: obj-*/gradle/build/mobile/android/geckoview/outputs/aar/*-x86.aar